# Generated by Django 2.1 on 2018-08-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='code',
            field=models.CharField(choices=[('Header', 'Header'), ('Feature', 'Feature'), ('Consultants', 'Consultants'), ('Recent Blog', 'Recent Blog'), ('Contact Us', 'Contact Us')], max_length=50),
        ),
    ]
