# Generated by Django 2.1 on 2018-08-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20180829_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='code',
            field=models.CharField(choices=[('Header', 'Header'), ('Feature', 'Feature'), ('Consultants', 'Consultants'), ('Recent Blog', 'Recent Blog'), ('Contact Us', 'Contact Us'), ('Footer', 'Footer')], max_length=50),
        ),
    ]
