# Generated by Django 2.1.1 on 2018-09-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_auto_20180906_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
